databases:
  - name: placementapidb
    plan: free
    databaseName: placementapi
    user: placementapi

services:
  - type: web
    plan: free
    name: placementapi
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn PlacementApi.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: placementapidb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4